name: Publish release candidate build artifact for sui catchup

on:
  push:
    tags:
      - rc*

jobs:
  build:
    runs-on: [ubuntu-20.04]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup go env
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          check-latest: true

      - name: build binaries
        run: go build -v ./...

      - name: publish artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: binaries
          path:
            - sui-catchup

