---
name: GoReleaser config check
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - .goreleaser.yaml
  pull_request:
    paths:
      - .goreleaser.yaml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  goreleaser-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: goreleaser check
        run: goreleaser check
