name: Release sui-catchup

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: [ubuntu-20.04]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup go env
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          check-latest: true

      - name: build binaries
        run: go build -v ./...

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sui-catchup

